# Generated by Django 4.2.1 on 2023-05-27 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Название вложения")),
                (
                    "attachment",
                    models.FileField(
                        max_length=200, upload_to="attachment/", verbose_name="Вложение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вложение",
                "verbose_name_plural": "Вложения",
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Название шаблона")),
                (
                    "template",
                    models.FileField(
                        max_length=200,
                        upload_to="templates/",
                        verbose_name="HTML шаблон письма",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон",
                "verbose_name_plural": "Шаблоны",
            },
        ),
        migrations.CreateModel(
            name="EmailToSend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confirm_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка для подтверждения"
                    ),
                ),
                (
                    "is_high_priority",
                    models.BooleanField(
                        default=False, verbose_name="Высокий приоритет"
                    ),
                ),
                (
                    "attachments",
                    models.ManyToManyField(
                        to="emails.attachment", verbose_name="Вложения"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emails",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="recipient_emails",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатели",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="emails.template",
                        verbose_name="Шаблон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Письмо для отправки",
                "verbose_name_plural": "Письма для отправки",
            },
        ),
    ]
